plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - EULA.md
  - GDPR.md
  - Privacy Policy.md
  - ASHT.md
  
